import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          type="module"
          src={"https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"}
          strategy="afterInteractive" // lazyOnload, afterInteractive
        />
        <Script
          noModule
          src={"https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"}
          strategy="afterInteractive" // lazyOnload, afterInteractive
        />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
